In [1]:
# Importing tensorflow
import tensorflow as tf

2024-07-05 22:06:09.221925: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-07-05 22:06:09.307633: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-07-05 22:06:09.397155: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:479] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-05 22:06:09.489921: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:10575] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-05 22:06:09.490465: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1442] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-05 22:06:09.636572: I tensorflow/core/platform/cpu_feature_guard.cc:

# Tensors

In [2]:
# 0 Dimensional tensor
d0 = tf.ones((1,))
print(d0)

tf.Tensor([1.], shape=(1,), dtype=float32)


In [3]:
# 1 Dimensional tensor
d1 = tf.ones((2,1))
print(d1)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [4]:
# 2 Dimensional tensor
d2 = tf.ones((2,2))
print(d2)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [5]:
# 3 Dimensional tensor
d3 = tf.ones((2,2,2))
print(d3)

tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)


In [6]:
# using the numpy method to print the tensor
print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [7]:
# A4 Dimensional tensor
exampleDimension = tf.ones(((1,2,3,4)))
print(exampleDimension)                           

tf.Tensor(
[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]], shape=(1, 2, 3, 4), dtype=float32)


# Constants and Variables

In [8]:
# Define a variable
a0 = tf.Variable([1,2,3,4,5,6],dtype=tf.float32)
a1 = tf.Variable([1,2,3,4,5,6],dtypes=tf.int16)

print(a0)
print(a1)

<tf.Variable 'Variable:0' shape=(6,) dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>


In [9]:
# Define a constant
b = tf.constant(2,tf.float32)

print(b)

tf.Tensor(2.0, shape=(), dtype=float32)


In [10]:
# compute their product
c0 = tf.multiply(a0,b)
c1 = a0*b

print(c1)

tf.Tensor([ 2.  4.  6.  8. 10. 12.], shape=(6,), dtype=float32)


# Basic Operations

### Applying the addition operator
- The add() operation performs element-wise addition with two tensors.
- Element-wise addition requires both tensors to have the same shape.
- The add() operator is overloaded

In [11]:
# import constant and add from tensorflow
from tensorflow import constant,add

In [12]:
# define 0-dimensional tensors
A0 = constant([1])
B0 = constant([2])

# define 1-dimensional tensor
A1 = constant([1, 2])
B1 = constant([3, 4])

# define 2-dimensional tensor
A2 = constant([[1, 2],[3, 4]])
B2 = constant([[5, 6],[7, 8]])

# perform tensor addition with add
C0 = add(A0,B0)
C1 = add(A1,B1)
C2 = add(A2,B2)

# print the reuslt
print('\n The value of C0 is: ',C0)
print('\n The value of C1 is: ',C1)
print('\n The value of C2 is: ',C2)


 The value of C0 is:  tf.Tensor([3], shape=(1,), dtype=int32)

 The value of C1 is:  tf.Tensor([4 6], shape=(2,), dtype=int32)

 The value of C2 is:  tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


### How to perform multiplication in TensorFlow
- Tensors multiplied using multiply() operation must have the same shape eg [1,2,3] and [3,4,5]
- The matmul(A,B) operations multiplies A by B and the number of columns of A must equal the number of rows of B.

In [13]:
# import operators from tensorflow
from tensorflow import ones,matmul,multiply

A0 = ones(1)
A31 = ones([3,1])
A34 = ones([3,4])
A43 = ones([4,3])

# Valid operations
print(multiply(A0,A0))
print(multiply(A31,A31))

print(matmul(A43,A34))

tf.Tensor([1.], shape=(1,), dtype=float32)
tf.Tensor(
[[1.]
 [1.]
 [1.]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]], shape=(4, 4), dtype=float32)


### Summing over tensor dimensions
- The reduce_sum() operator sums over the dimensions of a tensor
- reduce_sum(A) sums over all dimensions of A
- reduce_sum(A,i) sums over dimension i

In [14]:
# import operations from tensorflow
from tensorflow import ones,reduce_sum,constant,ones_like

# Define a 2x3x4 tensor of ones
A = ones([2,3,4])

# sum over all dimensions
B = reduce_sum(A)

# Sum over dimensions 0,1,2
B0 = reduce_sum(A,0)
B1 = reduce_sum(A,1)
B2 = reduce_sum(A,2)

print(f"The result of B0 is {B0}")
print(f"The result of B1 is {B1}")
print(f"The result of B2 is {B2}")

The result of B0 is [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
The result of B1 is [[3. 3. 3. 3.]
 [3. 3. 3. 3.]]
The result of B2 is [[4. 4. 4.]
 [4. 4. 4.]]


### Performing element-wise multiplication
- Define the tensors A1 and A23 as constants.
- Set B1 to be a tensor of ones with the same shape as A1.
- Set B23 to be a tensor of ones with the same shape as A23.
- Set C1 and C23 equal to the element-wise products of A1 and B1, and A23 and B23, respectively.

In [15]:
# Define tensors A1 and A23 as constants
A1 = constant([1,2,3,4])
A23 = constant([[1,2,3],[1,6,4]])

# Define B1 and B23 to have the correct shape
B1 = ones_like([1,2,3,4])
B23 = ones_like([[1,2,3],[4,5,6]])

# Perform element-wise multiplication
C1 = multiply(A1,B1)
C23 = multiply(A23,B23)

# Print the tensors C1 and C23
print('\n C1: {}'.format(C1.numpy()))
print('\n C23: {}'.format(C23.numpy()))


 C1: [1 2 3 4]

 C23: [[1 2 3]
 [1 6 4]]


### Making predictions with matrix multiplication
- Define features, params, and bill as constants.
- Compute the predicted value vector, billpred, by multiplying the input data, features, by the parameters, params. Use matrix multiplication, rather than the element-wise product.
- Define error as the targets, bill, minus the predicted values, billpred.

In [16]:
# Define features, params, and bill as constants
features = constant([[2,24],[2,26],[2,57],[1,37]])
params = constant([[1000],[150]])
bill = constant([[3913],[2682],[8617],[64400]])

# Compute billpred using features and params
billpred = matmul(features,params)

# Compute and print the error
error = bill - billpred

print(bill.numpy())
print(billpred.numpy())

print(error.numpy())

[[ 3913]
 [ 2682]
 [ 8617]
 [64400]]
[[ 5600]
 [ 5900]
 [10550]
 [ 6550]]
[[-1687]
 [-3218]
 [-1933]
 [57850]]


### Gradients in Tensorflow
- Much of the differentiation you do in deep learning models will be handled by high level APIs; however, gradient tape remains an invaluable tool for building advanced and custom models.

In [17]:
# import tensorflow
# import tensorflow as tf

# Define x
x = tf.Variable(-1.0)

# Define y within instance of  Gradient Tape
with tf.GradientTape() as tape:
    tape.watch(x)
    y = tf.multiply(x,x)

# Evaluate the gradient of y at x = -1
g = tape.gradient(y,x)
print(g.numpy())

-2.0


### How to rescale a grayscale image
- We will create a random grayscale image by drawing numbers from the set of integers between 0 and 255. We will use these to populate a 2 by 2 matrix. We can then reshape this into a 4 by 1 vector.

In [19]:
# Import tensorflow as tf

# Generate grayscale image
gray = tf.random.uniform([2,2],maxval=255,dtype='int32')

# Reshape grayscale image
gray = tf.reshape(gray,[2*2,1])

# print
print(gray.numpy())

[[119]
 [229]
 [  4]
 [ 63]]


### How to rescale a color image

In [20]:
# Import tensorflow as tf

# Generate color image
color = tf.random.uniform([2,2,3],maxval=255,dtype='int32')

# Reshape color image
color = tf.reshape(color,[2*2,3])

# print
print(color.numpy())

[[ 31 231  92]
 [ 61 179 218]
 [172 145 110]
 [  8 191 168]]


### Reshaping tensors
- Reshape gray_tensor from a 28x28 matrix into a 784x1 vector named gray_vector.
- Reshape color_tensor from a 28x28x3 tensor into a 2352x1 vector named color_vector.

In [25]:
# Import tensorflow

# Generate gray and color tensors
gray_tensor = tf.random.uniform([1,4],maxval=255,dtype='int32')
color_tensor = tf.random.uniform([1,2,3],maxval=255,dtype='int32')

# Reshape the grayscale image tensor into a vector
gray_vector = tf.reshape(gray_tensor,(4,1))
color_vector = tf.reshape(color_tensor,(6,1))

# print result
print(gray_vector.numpy())
print(color_vector.numpy())

[[253]
 [187]
 [200]
 [118]]
[[186]
 [ 17]
 [ 76]
 [241]
 [247]
 [176]]


### Working with image data
- The model, model, is 1x3 tensor, but should be a 3x1. Reshape model.
- Perform a matrix multiplication of the 3x3 tensor, letter, by the 3x1 tensor, model.
- Sum over the resulting tensor, output, and assign this value to prediction.
- Print prediction using the .numpy() method to determine whether letter is K.

In [28]:
# model is a 1x3 tensor
model = tf.random.uniform([1,3],maxval=255,dtype='int32')

# Reshape model from a 1x3 to a 3x1 tensor
model = tf.reshape(model,(3*1,1))

# letter be a 3x3 tensor
letter = tf.random.uniform([3,3],maxval=255,dtype='int32')

# Multiply letter by model
output = tf.matmul(letter,model)

# Sum over output and print prediction using the numpy method
prediction = reduce_sum(output)
print(prediction.numpy())

274596
